FROM labtainer.network.ssh

ARG lab
ARG labdir
ARG imagedir
ARG user_name=ubuntu
ARG password=ubuntu
ARG version
LABEL version=$version

ADD $labdir/$lab.tar.gz /home/$user_name
RUN echo "$user_name:${password:-ubuntu}" | chpasswd
