FROM labtainer.network.ssh

ARG lab
ARG labdir
ARG imagedir
ARG user_name=ubuntu
ARG password=ubuntu
ARG version
LABEL version=$version

RUN id "$user_name" >/dev/null 2>&1 || useradd -m -s /bin/bash "$user_name"
ADD $labdir/$lab.tar.gz /home/$user_name
RUN usermod -p "$(openssl passwd -1 "${password:-ubuntu}")" "$user_name" && \
    chown -R "$user_name:$user_name" /home/$user_name
